server:
  port: 8102 #运行端口
spring:
  application:
    name: eureka-client #服务名称
eureka:
  instance:
    hostname: peer
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://peer1:8002/eureka/,http://peer2:8003/eureka/ #同时注册到两个注册中心